# Jekyll configuration

name: MhFTP
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
url: http://albertopires.github.io
#url: http://127.0.0.1:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: '/mhftp'
project: 'albertopires/mhftp'

social:
  github: albertopires
  stackoverflow: 2263312/alberto-pires
  linkedin: alberto-pires-0443157
#  instagram: ''
#  lastfm: ''
#  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blanc to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: pygments
highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['LICENSE']
